import datetime

def write_to_file(command):
    try:
        # Extract actual text from command
        content = command.replace("write", "").strip()
        if not content:
            content = input("📝 MCP: What should I write in the file? ")

        # Optional: Add a title and timestamp
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        formatted_text = f"""
📄 MCP NOTE
----------------------------
Date: {now}

{content}

----------------------------
Generated by Sinchan
""".strip()

        with open("output.txt", "w", encoding="utf-8") as f:
            f.write(formatted_text)

        return "✅ MCP: Written to output.txt"
    except Exception as e:
        return f"❌ MCP: Failed to write: {e}"

def format_email(subject, idea, recipient_name, sender_name):
    return f"""
Hi {recipient_name},

{idea}

Best regards,  
{sender_name}
""".strip()
